/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState, useEffect } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";
import * as THREE from "three";
//import { useSpring, a } from "react-spring/three";


export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../../../coffre-minecraft.glb"
  );
  const actions = useRef();

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, -0.99, 0]} >
        <primitive object={nodes.Bone} />
        <primitive  object={nodes.Bone001} />
        <skinnedMesh
          castShadow
          receiveShadow
          material={materials.Material}
          geometry={nodes.Cube.geometry}
          skeleton={nodes.Cube.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../coffre-minecraft.glb");