/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState, useEffect } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";
import { useSpring, a } from "react-spring/three";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../../../coffre-minecraft.glb"
  );

  const handleOpen =()=> {
    props.setIsOpen(!props.isOpen)
  }
  const chestAnimation = useSpring({
    rotation: props.isOpen ? [0,0,0] : [1.61,0,0],
    position: props.isOpen ? [0,-1.5,0] : [0,0,0],
  })

  return (
    <group onClick={handleOpen} ref={group} {...props} dispose={null}>
      <group position={[0, -0.99, 0]} >
        <primitive object={nodes.Bone} />
        <a.primitive  
          rotation={chestAnimation.rotation}
          object={nodes.Bone001} />
        <skinnedMesh
          castShadow
          receiveShadow
          material={materials.Material}
          geometry={nodes.Cube.geometry}
          skeleton={nodes.Cube.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../../coffre-minecraft.glb");